In [12]:
from pathlib import Path
import polars as pl
from ucimlrepo import fetch_ucirepo # Official library to import dataset from ucimlrepo

In [13]:
# Fetch the dataset with this code 

# adult = fetch_ucirepo(id=2) 
  
# # data (as pandas dataframes) 
# X = adult.data.features 
# y = adult.data.targets 
  
# # metadata 
# print(adult.metadata) 
  
# # variable information 
# print(adult.variables)

In [14]:
# Instead of fetching the dataset again and again , I have simply downloaded the folder for the adult set .
# I will pe using the Path to import the set directly without any recurrent fetching.

In [15]:
BASE_PATH = Path.cwd().parent / "datasets" / "adult"

TRAIN_PATH = BASE_PATH / "adult.data"
TEST_PATH = BASE_PATH / "adult.test"

In [16]:
# Column names from adult.names : 
""" 
age: continuous.
workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
fnlwgt: continuous.
education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
education-num: continuous.
marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
sex: Female, Male.
capital-gain: continuous.
capital-loss: continuous.
hours-per-week: continuous.
native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.

"""

columns = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education-num",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital-gain",
    "capital-loss",
    "hours-per-week",
    "native-country"
]

In [35]:
# Best practice is to use exceptional handling here but for now just load the training and testing set 
train = pl.read_csv(TRAIN_PATH,has_header=False,new_columns=columns)
test = pl.read_csv(TEST_PATH,has_header=False,new_columns=columns,skip_rows=1)

# The dataset did not contain the column names but were given to us in a seperate txtfile.
# Also the y column had a corrupt first row which we skip for now.

In [27]:
train.shape

(32562, 15)

In [34]:
test.shape

(16282, 15)

In [29]:
train.head()

shape: (5, 15)
┌─────┬─────────────┬─────────┬────────────┬───┬─────────────┬────────────┬────────────┬───────────┐
│ age ┆ workclass   ┆ fnlwgt  ┆ education  ┆ … ┆ capital-los ┆ hours-per- ┆ native-cou ┆ column_15 │
│ --- ┆ ---         ┆ ---     ┆ ---        ┆   ┆ s           ┆ week       ┆ ntry       ┆ ---       │
│ i64 ┆ str         ┆ str     ┆ str        ┆   ┆ ---         ┆ ---        ┆ ---        ┆ str       │
│     ┆             ┆         ┆            ┆   ┆ str         ┆ str        ┆ str        ┆           │
╞═════╪═════════════╪═════════╪════════════╪═══╪═════════════╪════════════╪════════════╪═══════════╡
│ 39  ┆  State-gov  ┆  77516  ┆  Bachelors ┆ … ┆  0          ┆  40        ┆ United-Sta ┆  <=50K    │
│     ┆             ┆         ┆            ┆   ┆             ┆            ┆ tes        ┆           │
│ 50  ┆ Self-emp-no ┆  83311  ┆  Bachelors ┆ … ┆  0          ┆  13        ┆ United-Sta ┆  <=50K    │
│     ┆ t-inc       ┆         ┆            ┆   ┆             ┆            ┆ tes        ┆           │
│ 38  ┆  Private    ┆  215646 ┆  HS-grad   ┆ … ┆  0          ┆  40        ┆ United-Sta ┆  <=50K    │
│     ┆             ┆         ┆            ┆   ┆             ┆            ┆ tes        ┆           │
│ 53  ┆  Private    ┆  234721 ┆  11th      ┆ … ┆  0          ┆  40        ┆ United-Sta ┆  <=50K    │
│     ┆             ┆         ┆            ┆   ┆             ┆            ┆ tes        ┆           │
│ 28  ┆  Private    ┆  338409 ┆  Bachelors ┆ … ┆  0          ┆  40        ┆  Cuba      ┆  <=50K    │
└─────┴─────────────┴─────────┴────────────┴───┴─────────────┴────────────┴────────────┴───────────┘

In [33]:
test.head()

shape: (5, 15)
┌─────┬────────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬───────────┐
│ age ┆ workclass  ┆ fnlwgt  ┆ education   ┆ … ┆ capital-los ┆ hours-per- ┆ native-cou ┆ column_15 │
│ --- ┆ ---        ┆ ---     ┆ ---         ┆   ┆ s           ┆ week       ┆ ntry       ┆ ---       │
│ i64 ┆ str        ┆ str     ┆ str         ┆   ┆ ---         ┆ ---        ┆ ---        ┆ str       │
│     ┆            ┆         ┆             ┆   ┆ str         ┆ str        ┆ str        ┆           │
╞═════╪════════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪═══════════╡
│ 25  ┆  Private   ┆  226802 ┆  11th       ┆ … ┆  0          ┆  40        ┆ United-Sta ┆  <=50K.   │
│     ┆            ┆         ┆             ┆   ┆             ┆            ┆ tes        ┆           │
│ 38  ┆  Private   ┆  89814  ┆  HS-grad    ┆ … ┆  0          ┆  50        ┆ United-Sta ┆  <=50K.   │
│     ┆            ┆         ┆             ┆   ┆             ┆            ┆ tes        ┆           │
│ 28  ┆  Local-gov ┆  336951 ┆  Assoc-acdm ┆ … ┆  0          ┆  40        ┆ United-Sta ┆  >50K.    │
│     ┆            ┆         ┆             ┆   ┆             ┆            ┆ tes        ┆           │
│ 44  ┆  Private   ┆  160323 ┆ Some-colleg ┆ … ┆  0          ┆  40        ┆ United-Sta ┆  >50K.    │
│     ┆            ┆         ┆ e           ┆   ┆             ┆            ┆ tes        ┆           │
│ 18  ┆  ?         ┆  103497 ┆ Some-colleg ┆ … ┆  0          ┆  30        ┆ United-Sta ┆  <=50K.   │
│     ┆            ┆         ┆ e           ┆   ┆             ┆            ┆ tes        ┆           │
└─────┴────────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴───────────┘

# EDA (Complete dataset)