In [150]:
from pathlib import Path
import polars as pl
import polars.selectors as cs
from ucimlrepo import fetch_ucirepo # Official library to import dataset from ucimlrepo

In [151]:
# Fetch the dataset with this code 

# adult = fetch_ucirepo(id=2) 
  
# # data (as pandas dataframes) 
# X = adult.data.features 
# y = adult.data.targets 
  
# # metadata 
# print(adult.metadata) 
  
# # variable information 
# print(adult.variables)

In [152]:
# Instead of fetching the dataset again and again , I have simply downloaded the folder for the adult set .
# I will pe using the Path to import the set directly without any recurrent fetching.

In [153]:
BASE_PATH = Path.cwd().parent / "datasets" / "adult"

TRAIN_PATH = BASE_PATH / "adult.data"
TEST_PATH = BASE_PATH / "adult.test"

In [154]:
# Column names from adult.names : 
""" 
age: continuous.
workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
fnlwgt: continuous.
education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
education-num: continuous.
marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
sex: Female, Male.
capital-gain: continuous.
capital-loss: continuous.
hours-per-week: continuous.
native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.

"""

columns = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education-num",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital-gain",
    "capital-loss",
    "hours-per-week",
    "native-country",
    "salary"
]

In [155]:
# Best practice is to use exceptional handling here but for now just load the training and testing set 
train = pl.read_csv(TRAIN_PATH,has_header=False,new_columns=columns)
test = pl.read_csv(TEST_PATH,has_header=False,new_columns=columns,skip_rows=1)

# The dataset did not contain the column names but were given to us in a seperate txtfile.
# Also the y column had a corrupt first row which we skip for now.

In [156]:
train.shape

(32562, 15)

In [157]:
test.shape

(16282, 15)

In [158]:
train.head()

shape: (5, 15)
┌─────┬──────────────┬─────────┬────────────┬───┬─────────────┬─────────────┬─────────────┬────────┐
│ age ┆ workclass    ┆ fnlwgt  ┆ education  ┆ … ┆ capital-los ┆ hours-per-w ┆ native-coun ┆ salary │
│ --- ┆ ---          ┆ ---     ┆ ---        ┆   ┆ s           ┆ eek         ┆ try         ┆ ---    │
│ i64 ┆ str          ┆ str     ┆ str        ┆   ┆ ---         ┆ ---         ┆ ---         ┆ str    │
│     ┆              ┆         ┆            ┆   ┆ str         ┆ str         ┆ str         ┆        │
╞═════╪══════════════╪═════════╪════════════╪═══╪═════════════╪═════════════╪═════════════╪════════╡
│ 39  ┆  State-gov   ┆  77516  ┆  Bachelors ┆ … ┆  0          ┆  40         ┆ United-Stat ┆  <=50K │
│     ┆              ┆         ┆            ┆   ┆             ┆             ┆ es          ┆        │
│ 50  ┆ Self-emp-not ┆  83311  ┆  Bachelors ┆ … ┆  0          ┆  13         ┆ United-Stat ┆  <=50K │
│     ┆ -inc         ┆         ┆            ┆   ┆             ┆             ┆ es          ┆        │
│ 38  ┆  Private     ┆  215646 ┆  HS-grad   ┆ … ┆  0          ┆  40         ┆ United-Stat ┆  <=50K │
│     ┆              ┆         ┆            ┆   ┆             ┆             ┆ es          ┆        │
│ 53  ┆  Private     ┆  234721 ┆  11th      ┆ … ┆  0          ┆  40         ┆ United-Stat ┆  <=50K │
│     ┆              ┆         ┆            ┆   ┆             ┆             ┆ es          ┆        │
│ 28  ┆  Private     ┆  338409 ┆  Bachelors ┆ … ┆  0          ┆  40         ┆  Cuba       ┆  <=50K │
└─────┴──────────────┴─────────┴────────────┴───┴─────────────┴─────────────┴─────────────┴────────┘

In [159]:
test.head()

shape: (5, 15)
┌─────┬────────────┬─────────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬─────────┐
│ age ┆ workclass  ┆ fnlwgt  ┆ education   ┆ … ┆ capital-los ┆ hours-per-w ┆ native-coun ┆ salary  │
│ --- ┆ ---        ┆ ---     ┆ ---         ┆   ┆ s           ┆ eek         ┆ try         ┆ ---     │
│ i64 ┆ str        ┆ str     ┆ str         ┆   ┆ ---         ┆ ---         ┆ ---         ┆ str     │
│     ┆            ┆         ┆             ┆   ┆ str         ┆ str         ┆ str         ┆         │
╞═════╪════════════╪═════════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════╡
│ 25  ┆  Private   ┆  226802 ┆  11th       ┆ … ┆  0          ┆  40         ┆ United-Stat ┆  <=50K. │
│     ┆            ┆         ┆             ┆   ┆             ┆             ┆ es          ┆         │
│ 38  ┆  Private   ┆  89814  ┆  HS-grad    ┆ … ┆  0          ┆  50         ┆ United-Stat ┆  <=50K. │
│     ┆            ┆         ┆             ┆   ┆             ┆             ┆ es          ┆         │
│ 28  ┆  Local-gov ┆  336951 ┆  Assoc-acdm ┆ … ┆  0          ┆  40         ┆ United-Stat ┆  >50K.  │
│     ┆            ┆         ┆             ┆   ┆             ┆             ┆ es          ┆         │
│ 44  ┆  Private   ┆  160323 ┆ Some-colleg ┆ … ┆  0          ┆  40         ┆ United-Stat ┆  >50K.  │
│     ┆            ┆         ┆ e           ┆   ┆             ┆             ┆ es          ┆         │
│ 18  ┆  ?         ┆  103497 ┆ Some-colleg ┆ … ┆  0          ┆  30         ┆ United-Stat ┆  <=50K. │
│     ┆            ┆         ┆ e           ┆   ┆             ┆             ┆ es          ┆         │
└─────┴────────────┴─────────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴─────────┘

In [160]:
train.null_count()

shape: (1, 15)
┌─────┬───────────┬────────┬───────────┬───┬──────────────┬───────────────┬───────────────┬────────┐
│ age ┆ workclass ┆ fnlwgt ┆ education ┆ … ┆ capital-loss ┆ hours-per-wee ┆ native-countr ┆ salary │
│ --- ┆ ---       ┆ ---    ┆ ---       ┆   ┆ ---          ┆ k             ┆ y             ┆ ---    │
│ u32 ┆ u32       ┆ u32    ┆ u32       ┆   ┆ u32          ┆ ---           ┆ ---           ┆ u32    │
│     ┆           ┆        ┆           ┆   ┆              ┆ u32           ┆ u32           ┆        │
╞═════╪═══════════╪════════╪═══════════╪═══╪══════════════╪═══════════════╪═══════════════╪════════╡
│ 1   ┆ 1         ┆ 1      ┆ 1         ┆ … ┆ 1            ┆ 1             ┆ 1             ┆ 1      │
└─────┴───────────┴────────┴───────────┴───┴──────────────┴───────────────┴───────────────┴────────┘

In [161]:
test.null_count()

shape: (1, 15)
┌─────┬───────────┬────────┬───────────┬───┬──────────────┬───────────────┬───────────────┬────────┐
│ age ┆ workclass ┆ fnlwgt ┆ education ┆ … ┆ capital-loss ┆ hours-per-wee ┆ native-countr ┆ salary │
│ --- ┆ ---       ┆ ---    ┆ ---       ┆   ┆ ---          ┆ k             ┆ y             ┆ ---    │
│ u32 ┆ u32       ┆ u32    ┆ u32       ┆   ┆ u32          ┆ ---           ┆ ---           ┆ u32    │
│     ┆           ┆        ┆           ┆   ┆              ┆ u32           ┆ u32           ┆        │
╞═════╪═══════════╪════════╪═══════════╪═══╪══════════════╪═══════════════╪═══════════════╪════════╡
│ 1   ┆ 1         ┆ 1      ┆ 1         ┆ … ┆ 1            ┆ 1             ┆ 1             ┆ 1      │
└─────┴───────────┴────────┴───────────┴───┴──────────────┴───────────────┴───────────────┴────────┘

In [162]:
# There is exactly a single row in each column containing a missing value. 
# We shall drop this rows before concating.
# It will also have no effect as the ration from null value rows and non null value rows is insignificant.

In [163]:
train = train.drop_nulls()
test = test.drop_nulls()

# EDA (Complete dataset)

In [164]:
# Now for further EDA analysis I will concat both the dataset .

In [165]:
df = pl.concat([train,test])

In [166]:
df.shape # The combined shape

(48842, 15)

In [167]:
df.head()

shape: (5, 15)
┌─────┬──────────────┬─────────┬────────────┬───┬─────────────┬─────────────┬─────────────┬────────┐
│ age ┆ workclass    ┆ fnlwgt  ┆ education  ┆ … ┆ capital-los ┆ hours-per-w ┆ native-coun ┆ salary │
│ --- ┆ ---          ┆ ---     ┆ ---        ┆   ┆ s           ┆ eek         ┆ try         ┆ ---    │
│ i64 ┆ str          ┆ str     ┆ str        ┆   ┆ ---         ┆ ---         ┆ ---         ┆ str    │
│     ┆              ┆         ┆            ┆   ┆ str         ┆ str         ┆ str         ┆        │
╞═════╪══════════════╪═════════╪════════════╪═══╪═════════════╪═════════════╪═════════════╪════════╡
│ 39  ┆  State-gov   ┆  77516  ┆  Bachelors ┆ … ┆  0          ┆  40         ┆ United-Stat ┆  <=50K │
│     ┆              ┆         ┆            ┆   ┆             ┆             ┆ es          ┆        │
│ 50  ┆ Self-emp-not ┆  83311  ┆  Bachelors ┆ … ┆  0          ┆  13         ┆ United-Stat ┆  <=50K │
│     ┆ -inc         ┆         ┆            ┆   ┆             ┆             ┆ es          ┆        │
│ 38  ┆  Private     ┆  215646 ┆  HS-grad   ┆ … ┆  0          ┆  40         ┆ United-Stat ┆  <=50K │
│     ┆              ┆         ┆            ┆   ┆             ┆             ┆ es          ┆        │
│ 53  ┆  Private     ┆  234721 ┆  11th      ┆ … ┆  0          ┆  40         ┆ United-Stat ┆  <=50K │
│     ┆              ┆         ┆            ┆   ┆             ┆             ┆ es          ┆        │
│ 28  ┆  Private     ┆  338409 ┆  Bachelors ┆ … ┆  0          ┆  40         ┆  Cuba       ┆  <=50K │
└─────┴──────────────┴─────────┴────────────┴───┴─────────────┴─────────────┴─────────────┴────────┘

In [168]:
# A quick initial analysis function 
def examine_dataframe(df):
    print("-"*100)
    print(f'NOTE : Column names will be converted to lower case and trimming all the white spaces.')
    print("-"*100)
    df.columns = [x.lower().strip().replace(" ","_") for x in df.columns]
    print(f"Dataframe shape : {df.shape}")
    print("-"*100)
    print(f"Memory Usage : {df.estimated_size("mb"):.2f} MB")
    print("-"*100)
    print(f"Column Dtypes: \n{df.dtypes}")
    print("-"*100)
    print(f'Quick overview of all columns: ')
    columns_df = pl.DataFrame({
    'column'           : df.columns,
    'dtype'            : [str(x) for x in df.dtypes],
    '#unique_values'   : [df[x].n_unique() for x in df.columns],
    '#non_null_values' : [df[x].count() for x in df.columns],
    '#null_values'     : [df[x].null_count() for x in df.columns],
    '%null_values'     : [f'{(df[x].null_count() / len(df) * 100):.5f}' for x in df.columns]
    })

    return (columns_df)

In [169]:
examine_dataframe(df)

----------------------------------------------------------------------------------------------------
NOTE : Column names will be converted to lower case and trimming all the white spaces.
----------------------------------------------------------------------------------------------------
Dataframe shape : (48842, 15)
----------------------------------------------------------------------------------------------------
Memory Usage : 5.28 MB
----------------------------------------------------------------------------------------------------
Column Dtypes:
[Int64, String, String, String, String, String, String, String, String, String, String, String, String, String, String]
----------------------------------------------------------------------------------------------------
Quick overview of all columns:

shape: (15, 6)
┌────────────────┬────────┬────────────────┬──────────────────┬──────────────┬──────────────┐
│ column         ┆ dtype  ┆ #unique_values ┆ #non_null_values ┆ #null_values ┆ %null_values │
│ ---            ┆ ---    ┆ ---            ┆ ---              ┆ ---          ┆ ---          │
│ str            ┆ str    ┆ i64            ┆ i64              ┆ i64          ┆ str          │
╞════════════════╪════════╪════════════════╪══════════════════╪══════════════╪══════════════╡
│ age            ┆ Int64  ┆ 74             ┆ 48842            ┆ 0            ┆ 0.00000      │
│ workclass      ┆ String ┆ 9              ┆ 48842            ┆ 0            ┆ 0.00000      │
│ fnlwgt         ┆ String ┆ 28523          ┆ 48842            ┆ 0            ┆ 0.00000      │
│ education      ┆ String ┆ 16             ┆ 48842            ┆ 0            ┆ 0.00000      │
│ education-num  ┆ String ┆ 16             ┆ 48842            ┆ 0            ┆ 0.00000      │
│ …              ┆ …      ┆ …              ┆ …                ┆ …            ┆ …            │
│ capital-gain   ┆ String ┆ 123            ┆ 48842            ┆ 0            ┆ 0.00000      │
│ capital-loss   ┆ String ┆ 99             ┆ 48842            ┆ 0            ┆ 0.00000      │
│ hours-per-week ┆ String ┆ 96             ┆ 48842            ┆ 0            ┆ 0.00000      │
│ native-country ┆ String ┆ 42             ┆ 48842            ┆ 0            ┆ 0.00000      │
│ salary         ┆ String ┆ 4              ┆ 48842            ┆ 0            ┆ 0.00000      │
└────────────────┴────────┴────────────────┴──────────────────┴──────────────┴──────────────┘

In [170]:
# A lot of value are in string including somen numeric columns as well.
# There is a certain row in the set which contains null values for every column .
# Rest other columns are non null.

# The dataset has a high cardinality columns .
# Suitable strategy has to be devised to handle each categorical column.

# Later modified the training and testing set to drop the rows immediately before concatination to ease our tasks

In [179]:
df.sample(5)

shape: (5, 15)
┌─────┬─────────────┬─────────┬────────────┬───┬─────────────┬─────────────┬─────────────┬─────────┐
│ age ┆ workclass   ┆ fnlwgt  ┆ education  ┆ … ┆ capital-los ┆ hours-per-w ┆ native-coun ┆ salary  │
│ --- ┆ ---         ┆ ---     ┆ ---        ┆   ┆ s           ┆ eek         ┆ try         ┆ ---     │
│ i64 ┆ str         ┆ str     ┆ str        ┆   ┆ ---         ┆ ---         ┆ ---         ┆ str     │
│     ┆             ┆         ┆            ┆   ┆ str         ┆ str         ┆ str         ┆         │
╞═════╪═════════════╪═════════╪════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════╡
│ 52  ┆  Local-gov  ┆  305053 ┆  HS-grad   ┆ … ┆  2051       ┆  40         ┆ United-Stat ┆  <=50K  │
│     ┆             ┆         ┆            ┆   ┆             ┆             ┆ es          ┆         │
│ 53  ┆ Federal-gov ┆  439263 ┆  Bachelors ┆ … ┆  0          ┆  40         ┆ United-Stat ┆  >50K.  │
│     ┆             ┆         ┆            ┆   ┆             ┆             ┆ es          ┆         │
│ 52  ┆  Private    ┆  204584 ┆  Bachelors ┆ … ┆  0          ┆  42         ┆ United-Stat ┆  <=50K  │
│     ┆             ┆         ┆            ┆   ┆             ┆             ┆ es          ┆         │
│ 47  ┆ Self-emp-no ┆  276087 ┆  HS-grad   ┆ … ┆  0          ┆  65         ┆ United-Stat ┆  <=50K. │
│     ┆ t-inc       ┆         ┆            ┆   ┆             ┆             ┆ es          ┆         │
│ 30  ┆  Private    ┆  154297 ┆  10th      ┆ … ┆  0          ┆  40         ┆ United-Stat ┆  <=50K  │
│     ┆             ┆         ┆            ┆   ┆             ┆             ┆ es          ┆         │
└─────┴─────────────┴─────────┴────────────┴───┴─────────────┴─────────────┴─────────────┴─────────┘

In [172]:
# This was just a guess but looking closely we found out that dropping nans was just not enough .
# It was a mere trap , the real missing values hiding beneath have also have a "?" symbol attached .

# We have to hunt these symbols and other suspects for cleaning.

In [182]:
df_clean = df.with_columns(
    cs.string().str.strip_chars()
)

rows_with_questions = df_clean.filter(
    pl.any_horizontal(cs.string() == "?")
)

print(rows_with_questions)

shape: (3_620, 15)
┌─────┬───────────┬────────┬──────────────┬───┬──────────────┬──────────────┬─────────────┬────────┐
│ age ┆ workclass ┆ fnlwgt ┆ education    ┆ … ┆ capital-loss ┆ hours-per-we ┆ native-coun ┆ salary │
│ --- ┆ ---       ┆ ---    ┆ ---          ┆   ┆ ---          ┆ ek           ┆ try         ┆ ---    │
│ i64 ┆ str       ┆ str    ┆ str          ┆   ┆ str          ┆ ---          ┆ ---         ┆ str    │
│     ┆           ┆        ┆              ┆   ┆              ┆ str          ┆ str         ┆        │
╞═════╪═══════════╪════════╪══════════════╪═══╪══════════════╪══════════════╪═════════════╪════════╡
│ 40  ┆ Private   ┆ 121772 ┆ Assoc-voc    ┆ … ┆ 0            ┆ 40           ┆ ?           ┆ >50K   │
│ 54  ┆ ?         ┆ 180211 ┆ Some-college ┆ … ┆ 0            ┆ 60           ┆ South       ┆ >50K   │
│ 31  ┆ Private   ┆ 84154  ┆ Some-college ┆ … ┆ 0            ┆ 38           ┆ ?           ┆ >50K   │
│ 18  ┆ Private   ┆ 226956 ┆ HS-grad      ┆ … ┆ 0            ┆ 30           ┆ ?           ┆ <=50K  │
│ 32  ┆ ?         ┆ 293936 ┆ 7th-8th      ┆ … ┆ 0            ┆ 40           ┆ ?           ┆ <=50K  │
│ …   ┆ …         ┆ …      ┆ …            ┆ … ┆ …            ┆ …            ┆ …           ┆ …      │
│ 21  ┆ ?         ┆ 212661 ┆ Some-college ┆ … ┆ 0            ┆ 30           ┆ United-Stat ┆ <=50K. │
│     ┆           ┆        ┆              ┆   ┆              ┆              ┆ es          ┆        │
│ 73  ┆ ?         ┆ 144872 ┆ HS-grad      ┆ … ┆ 0            ┆ 25           ┆ Canada      ┆ <=50K. │
│ 81  ┆ ?         ┆ 26711  ┆ Assoc-voc    ┆ … ┆ 0            ┆ 20           ┆ United-Stat ┆ <=50K. │
│     ┆           ┆        ┆              ┆   ┆              ┆              ┆ es          ┆        │
│ 50  ┆ Local-gov ┆ 139347 ┆ Masters      ┆ … ┆ 0            ┆ 40           ┆ ?           ┆ >50K.  │
│ 64  ┆ ?         ┆ 321403 ┆ HS-grad      ┆ … ┆ 0            ┆ 40           ┆ United-Stat ┆ <=50K. │
│     ┆           ┆        ┆              ┆   ┆              ┆              ┆ es          ┆        │
└─────┴───────────┴────────┴──────────────┴───┴──────────────┴──────────────┴─────────────┴────────┘

In [183]:
# We have like 3630 rows where values are missing and been given a placeholder "?" instead also with spaces