In [236]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import polars as pl
import seaborn as sns

In [237]:
df = pd.read_csv('wiki_messy.csv')

In [238]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [239]:
df.columns

Index(['Rank', 'Peak', 'All Time Peak', 'Actual gross',
       'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)',
       'Shows', 'Average gross', 'Ref.'],
      dtype='str')

In [240]:
df.columns = df.columns.str.lower().str.replace(' ',"_").str.replace(r'\xa0','_',regex=True).str.replace('.',"")

In [241]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   rank                              20 non-null     int64
 1   peak                              9 non-null      str
 2   all_time_peak                     6 non-null      str
 3   actual_gross                      20 non-null     str
 4   adjusted_gross_(in_2022_dollars)  20 non-null     str
 5   artist                            20 non-null     str
 6   tour_title                        20 non-null     str
 7   year(s)                           20 non-null     str
 8   shows                             20 non-null     int64
 9   average_gross                     20 non-null     str
 10  ref                               20 non-null     str
dtypes: int64(2), str(9)
memory usage: 1.8 KB

In [242]:
print(df['peak'].str.replace(r'\d','X',regex=True).value_counts())
print('-'*145)
print(df['all_time_peak'].str.replace(r'\d','X',regex=True).value_counts())
print('-'*145)
print(df['ref'].str.replace(r'\d','X',regex=True).value_counts())
print('-'*145)

peak
X[X]     4
X        2
X[XX]    2
X[c]     1
Name: count, dtype: int64
-------------------------------------------------------------------------------------------------------------------------------------------------
all_time_peak
X[X]      2
XX[X]     2
X         1
XX[XX]    1
Name: count, dtype: int64
-------------------------------------------------------------------------------------------------------------------------------------------------
ref
[XX]        10
[X]          8
[XX][XX]     1
[d]          1
Name: count, dtype: int64
-------------------------------------------------------------------------------------------------------------------------------------------------

In [243]:
print(df['actual_gross'].str.replace(r'\d','x',regex=True).value_counts())
print('-'*145)
print(df['adjusted_gross_(in_2022_dollars)'].str.replace(r'\d','X',regex=True).value_counts())
print('-'*145)
print(df['average_gross'].str.replace(r'\d','X',regex=True).value_counts())

actual_gross
$xxx,xxx,xxx       18
$xxx,xxx,xxx[b]     1
$xxx,xxx,xxx[e]     1
Name: count, dtype: int64
-------------------------------------------------------------------------------------------------------------------------------------------------
adjusted_gross_(in_2022_dollars)
$XXX,XXX,XXX    20
Name: count, dtype: int64
-------------------------------------------------------------------------------------------------------------------------------------------------
average_gross
$X,XXX,XXX     17
$XX,XXX,XXX     2
$XXX,XXX        1
Name: count, dtype: int64

In [244]:
df['actual_gross'] = df['actual_gross'].str.findall(r'[0-9]').str.join('').astype('int')

In [245]:
df['adjusted_gross_(in_2022_dollars)'] = df['adjusted_gross_(in_2022_dollars)'].str.findall(r'[0-9]').str.join('').astype('int')

In [246]:
df['average_gross'] = df['average_gross'].str.findall(r'[0-9]').str.join('').astype('int')

In [247]:
#------------------------------------------------------------------------------------------------------------------------------------------#

In [248]:
df['peak'] = pd.to_numeric(df['peak'].str.extract(r'^([^\[]+)')[0],errors='coerce').astype('Int64')

In [249]:
df['all_time_peak'] = pd.to_numeric(df['all_time_peak'].str.extract(r'^([^\[]+)')[0],errors='coerce').astype('Int64')

In [250]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   rank                              20 non-null     int64
 1   peak                              9 non-null      Int64
 2   all_time_peak                     6 non-null      Int64
 3   actual_gross                      20 non-null     int64
 4   adjusted_gross_(in_2022_dollars)  20 non-null     int64
 5   artist                            20 non-null     str
 6   tour_title                        20 non-null     str
 7   year(s)                           20 non-null     str
 8   shows                             20 non-null     int64
 9   average_gross                     20 non-null     int64
 10  ref                               20 non-null     str
dtypes: Int64(2), int64(5), str(4)
memory usage: 1.9 KB

In [251]:
df.head()

,rank,peak,all_time_peak,actual_gross,adjusted_gross_(in_2022_dollars),artist,tour_title,year(s),shows,average_gross,ref
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour †,2023–2024,56,13928571,[1]
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,[3]
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,4835294,[6]
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,[7]
4,5,2,<NA>,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,[8]

In [252]:
df['year(s)'].str.replace(r'\d','x',regex=True).value_counts()

year(s)
xxxx–xxxx    14
xxxx          6
Name: count, dtype: int64

In [265]:
df['year_start'] = df['year(s)'].str.split('–').str[0]
df['year_end'] = df['year(s)'].str.split('–').str[1]

In [268]:
df = df.drop(columns=['year(s)','ref'])

In [266]:
df.head()

,rank,peak,all_time_peak,actual_gross,adjusted_gross_(in_2022_dollars),artist,tour_title,year(s),shows,average_gross,ref,year_start,year_end
0,1,1,2,780000000,780000000,Taylor Swift,The Eras Tour †,2023–2024,56,13928571,[1],2023,2024
1,2,1,7,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,[3],2023,NaN
2,3,1,2,411000000,560622615,Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,4835294,[6],2008,2009
3,4,2,10,397300000,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,[7],2018,2019
4,5,2,<NA>,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,[8],2018,NaN