In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split,cross_val_score

In [2]:
df = pd.read_csv('covid_19_data.csv')

In [3]:
df

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
306424,306425,05/29/2021,Zaporizhia Oblast,Ukraine,2021-05-30 04:20:55,102641.0,2335.0,95289.0
306425,306426,05/29/2021,Zeeland,Netherlands,2021-05-30 04:20:55,29147.0,245.0,0.0
306426,306427,05/29/2021,Zhejiang,Mainland China,2021-05-30 04:20:55,1364.0,1.0,1324.0
306427,306428,05/29/2021,Zhytomyr Oblast,Ukraine,2021-05-30 04:20:55,87550.0,1738.0,83790.0
306428,306429,05/29/2021,Zuid-Holland,Netherlands,2021-05-30 04:20:55,391559.0,4252.0,0.0

In [4]:
df.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   SNo              306429 non-null  int64
 1   ObservationDate  306429 non-null  str
 2   Province/State   228326 non-null  str
 3   Country/Region   306429 non-null  str
 4   Last Update      306429 non-null  str
 5   Confirmed        306429 non-null  float64
 6   Deaths           306429 non-null  float64
 7   Recovered        306429 non-null  float64
dtypes: float64(3), int64(1), str(4)
memory usage: 18.7 MB

In [6]:
# There are missing value columns

In [7]:
df = df.drop('SNo',axis=1)

In [9]:
df.sample()

,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
264671,04/05/2021,French Polynesia,France,2021-04-06 04:20:32,18633.0,141.0,4842.0

In [14]:
df['ObservationDate']  =  pd.to_datetime(df['ObservationDate'],errors='raise')
# There is no error as errors were not raised

In [16]:
df['ObservationDate'].info()
# This is a valauable piece of information as we are dealing with time series data

<class 'pandas.Series'>
RangeIndex: 306429 entries, 0 to 306428
Series name: ObservationDate
Non-Null Count   Dtype
--------------   -----
306429 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 2.3 MB

In [17]:
df.nunique()

ObservationDate       494
Province/State        736
Country/Region        229
Last Update          1905
Confirmed          107146
Deaths              20089
Recovered           74541
dtype: int64

In [28]:
df['Confirmed'] = pd.to_numeric(df['Confirmed'],errors='raise',downcast='integer')

In [31]:
df['Deaths'] = pd.to_numeric(df['Deaths'],errors='raise',downcast='integer')

In [35]:
df['Recovered'] = pd.to_numeric(df['Recovered'],errors='raise',downcast='integer')

In [36]:
df.head()

,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,2020-01-22,Anhui,Mainland China,1/22/2020 17:00,1,0,0
1,2020-01-22,Beijing,Mainland China,1/22/2020 17:00,14,0,0
2,2020-01-22,Chongqing,Mainland China,1/22/2020 17:00,6,0,0
3,2020-01-22,Fujian,Mainland China,1/22/2020 17:00,1,0,0
4,2020-01-22,Gansu,Mainland China,1/22/2020 17:00,0,0,0