In [40]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('datasets\Uncleaned_DS_jobs.csv',index_col='index')

In [42]:
df.shape

(672, 14)

In [43]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors'],
      dtype='str')

In [44]:
# Header cleaning
df.columns = df.columns.str.lower().str.replace(' ','_')

In [45]:
df.head()

,job_title,salary_estimate,job_description,rating,company_name,location,headquarters,size,founded,type_of_ownership,industry,sector,revenue,competitors
index,,,,,,,,,,,,,,
0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [46]:
df.tail()

,job_title,salary_estimate,job_description,rating,company_name,location,headquarters,size,founded,type_of_ownership,industry,sector,revenue,competitors
index,,,,,,,,,,,,,,
667,Data Scientist,$105K-$167K (Glassdoor est.),Summary\n\nWe’re looking for a data scientist ...,3.6,TRANZACT\n3.6,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
668,Data Scientist,$105K-$167K (Glassdoor est.),Job Description\nBecome a thought leader withi...,-1.0,JKGT,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
669,Data Scientist,$105K-$167K (Glassdoor est.),Join a thriving company that is changing the w...,-1.0,AccessHope,"Irwindale, CA",-1,-1,-1,-1,-1,-1,-1,-1
670,Data Scientist,$105K-$167K (Glassdoor est.),100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated\n5.0,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,-1,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),-1
671,Data Scientist,$105K-$167K (Glassdoor est.),Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),-1

In [47]:
# Notice that there is -1 in many rows this is a sign that data is missing there .

In [48]:
df.isna().sum() # This is just a scam for now as we know that data is having -1 as na

job_title            0
salary_estimate      0
job_description      0
rating               0
company_name         0
location             0
headquarters         0
size                 0
founded              0
type_of_ownership    0
industry             0
sector               0
revenue              0
competitors          0
dtype: int64

In [49]:
# So to actually get the nan we will do some replacements.
# Twice cause I want to make sure both string and numeric datatype is handled.
# Note : There is no data that might have -1 as valid data here so replacing is fine .

df = df.replace(-1,np.nan)
df = df.replace('-1',np.nan)

In [50]:
df.isna().sum()/len(df)*100 
# Now this is the reality, or who knows something else may be lurking underneath ; If we will find it later.

job_title             0.000000
salary_estimate       0.000000
job_description       0.000000
rating                7.440476
company_name          0.000000
location              0.000000
headquarters          4.613095
size                  4.017857
founded              17.559524
type_of_ownership     4.017857
industry             10.565476
sector               10.565476
revenue               4.017857
competitors          74.553571
dtype: float64

In [51]:
# For further steps I use data wrangler for EDA

In [52]:
df['salary_estimate'].str.split(" ")[0][0]

'$137K-$171K'

In [53]:
df['salary_estimate'] = df['salary_estimate'].str.split(" ").str[0] # Some Standard Cleaning for Salary Estimate

In [54]:
df.sample()

,job_title,salary_estimate,job_description,rating,company_name,location,headquarters,size,founded,type_of_ownership,industry,sector,revenue,competitors
index,,,,,,,,,,,,,,
196,"Health Plan Data Analyst, Sr",$56K-$97K,"Title: Health Plan Data Analyst, Sr\n\nCook Ch...",3.8,Cook Children's Health Care System\n3.8,"Fort Worth, TX","Fort Worth, TX",5001 to 10000 employees,1918.0,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),"Children's Health, Texas Health Resources, Bay..."

In [55]:
# There is strangely the rating again specified in the company name so we are gonna remove it . 
df['company_name'].str.split('\n').str[0]

index
0               Healthfirst
1                   ManTech
2            Analysis Group
3                   INFICON
4        Affinity Solutions
               ...
667                TRANZACT
668                    JKGT
669              AccessHope
670    ChaTeck Incorporated
671           1-800-Flowers
Name: company_name, Length: 672, dtype: object

In [56]:
df['company_name'] = df['company_name'].str.split('\n').str[0]

In [57]:
df.sample(3)

,job_title,salary_estimate,job_description,rating,company_name,location,headquarters,size,founded,type_of_ownership,industry,sector,revenue,competitors
index,,,,,,,,,,,,,,
193,Data Scientist,$56K-$97K,Job Description\nClient JD below:\n\nWe need a...,5.0,SkillSoniq,"San Francisco, CA","Jersey City, NJ",Unknown,NaN,Company - Public,NaN,NaN,Unknown / Non-Applicable,NaN
589,Hydrogen/Tritium Materials Scientist (Experien...,$138K-$158K,:\n\nWe need a R&D Materials Scientist to lead...,3.8,Sandia National Laboratories,"Livermore, CA","Albuquerque, NM",10000+ employees,1949.0,Government,Federal Agencies,Government,$2 to $5 billion (USD),"Los Alamos National Laboratory, Lawrence Liver..."
634,Data Scientist,$92K-$155K,"Overview:\n\n\nGood people, working with good ...",2.5,KeHE Distributors,"Naperville, IL","Naperville, IL",5001 to 10000 employees,1954.0,Company - Private,Wholesale,Business Services,Unknown / Non-Applicable,"United Natural Foods, US Foods, DPI Specialty ..."

In [58]:
# Found another thing now that the revenue column have rows with value : Unknown / Non-Applicable which are also nan so we must handle this too.

In [59]:
df['revenue'] = df['revenue'].replace('Unknown / Non-Applicable',np.nan)

In [60]:
df.isna().sum()/len(df)*100  
# As we can see the Revenue null values have spiked .

job_title             0.000000
salary_estimate       0.000000
job_description       0.000000
rating                7.440476
company_name          0.000000
location              0.000000
headquarters          4.613095
size                  4.017857
founded              17.559524
type_of_ownership     4.017857
industry             10.565476
sector               10.565476
revenue              35.714286
competitors          74.553571
dtype: float64

In [61]:
df.sample(3)

,job_title,salary_estimate,job_description,rating,company_name,location,headquarters,size,founded,type_of_ownership,industry,sector,revenue,competitors
index,,,,,,,,,,,,,,
121,Senior Data Engineer,$99K-$132K,About Scoop\n\nScoop brings co-workers and nei...,4.7,Scoop,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2015.0,Company - Private,Internet,Information Technology,NaN,NaN
184,Senior Data Analyst,$56K-$97K,About us\n\n\nLife360 brings families closer w...,3.9,Life360,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2008.0,Company - Public,Internet,Information Technology,NaN,NaN
158,Machine Learning Engineer,$101K-$165K,Overview\n\nRadical Convergence is a fast-pace...,NaN,Radical Convergence,"Reston, VA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN